name: Build and Publish BookMate to Master

# يعمل عند كل push على الفرع front
on:
  push:
    branches: [ Front ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ استنساخ الريبو
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2️⃣ إعداد .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'  # عدّل حسب نسخة مشروعك

    # 3️⃣ استعادة الحزم
    - name: Restore dependencies
      run: dotnet restore

    # 4️⃣ بناء ونشر المشروع
    - name: Build and Publish
      run: dotnet publish -c Release -o publish

    # 5️⃣ رفع ملفات Publish إلى فرع master
    - name: Push Publish to Master
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git checkout -B master
        cp -r publish/* .
        git add .
        git commit -m "Publish BookMate build to master"
        git push -f origin master
